### ISSUE TITLE
نمایش ایکون

### ISSUE THREAD

**Issue by sajjadmrx** [DnsChanger/dnsChanger-desktop#1]
ایکون در حالت production نمایش داده نمیشه

**Comment by im-parsa** [comment]
نمایش آیکون در تمامی حالت ها و در تمام سیستم عامل ها فیکس شد در pr جدید

**Comment by sajjadmrx** [comment]
> نمایش آیکون در تمامی حالت ها و در تمام سیستم عامل ها فیکس شد در pr جدید

![image](https://user-images.githubusercontent.com/66132114/226174174-9fd336e0-fb98-4a65-9147-4acec1cf64d5.png)
![image](https://user-images.githubusercontent.com/66132114/226174276-4695a101-895e-4500-a514-2bf198bb92f4.png)

سلام, ممنون بابت مشارکت 🖐️🛠️
اما همچنان در taskbar و taskManager ایکون نمایش داده نمیشه !
#4

**Comment by im-parsa** [comment]
> 

![image](https://user-images.githubusercontent.com/69428909/226175888-edf4b2d6-415c-433f-8ac7-77198ed8e921.png)
![image](https://user-images.githubusercontent.com/69428909/226175894-524a3724-f262-48da-9994-c3aba2937899.png)


روی ویندوز ۱۱، ۱۰ و اوبونتو فیکس بود حالا شما سیستم عاملتون چیه که بررسی کنم

**Comment by sajjadmrx** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/69428909/226175888-edf4b2d6-415c-433f-8ac7-77198ed8e921.png) ![image](https://user-images.githubusercontent.com/69428909/226175894-524a3724-f262-48da-9994-c3aba2937899.png)
> 
> روی ویندوز ۱۱، ۱۰ و اوبونتو فیکس بود حالا شما سیستم عاملتون چیه که بررسی کنم

ویندوز ۱۱
لطفا در حالت پروداکشن تست کنید و با `npm run make `

**Comment by im-parsa** [comment]
![image](https://user-images.githubusercontent.com/69428909/226266630-0e308e87-939b-4ebc-b8c5-f1a412c7fe0d.png)

در pr جدید این مشکل رو حل کردم
