### ISSUE TITLE
[Bug]:The donate link in read.me get 404

### ISSUE THREAD

**Issue by SaeedSaedi** [DnsChanger/dnsChanger-desktop#100]
### 🤔 Is there an existing issue for this?

- [x] I have searched the existing issues

### 📝 Discription

The donate link in read.me return 404 from [daramet.com](https://daramet.com/dnschanger)
so please check the link and add more way for donation if possible 

### 💻 In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
Hey! Thanks a lot for the support 💚🙏

I actually changed the link but forgot to update it here 🥸

new link: https://daramet.com/sajjadmrx

**Comment by SaeedSaedi** [comment]
No problem at all! Thanks for updating the link. I’ll make sure to use the new one moving forward. 😊

Best of luck with everything! 💚
