### ISSUE TITLE
مشکل اتصال در ویندوز 11

### ISSUE THREAD

**Issue by Sky-Kurt** [DnsChanger/dnsChanger-desktop#104]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

وصل نمیشه 

![bug](https://github.com/user-attachments/assets/22c0707c-bf62-40a4-9383-baa9d5cb9294)

توی ویندوز 10 این مشکل نبود و کاملا راحت کار میکرد ولی توی این ویندوز این مشکل هست
الان اینجا قسمت شبکه ها نمیاد که توی ویندوز 10 من با این قسمت کار کردم و هیچ مشکلی نداشت

![network](https://github.com/user-attachments/assets/8d2c5b05-222e-40e8-9693-54acf91bc07b)

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
duplicate #74
