### ISSUE TITLE
unknown error on windows

### ISSUE THREAD

**Issue by ErfanTech** [DnsChanger/dnsChanger-desktop#11]
![Screenshot (674)](https://github.com/DnsChanger/dnsChanger-desktop/assets/108360299/8554c175-ef17-4207-a7c1-f21bec795ff7)

**Comment by xmha97** [comment]
سلام عرفان جان @ErfanTech
من آخرین نسخه را نصب کردم و دیدم اپ به درستی کار می‌کنه.
دوباره اپ را نصب کنید و ببینید در نسخه‌ی جدید مشکل برطرف شده است یا نه؟
اگه مشکل حل شده بود، این ایشو را ببندید.
