### ISSUE TITLE
Minimize to tray and Update button

### ISSUE THREAD

**Issue by BlackCharon142** [DnsChanger/dnsChanger-desktop#14]
I've been using this program for a while now, and I think the most noticeable thing is first the app is always in the taskbar, and second, there needs to be an update button aside from the auto-update
other than that it's a useful tool

**Comment by BlackCharon142** [comment]
Update: forgot to check the latest update which does have an update button
but the minimize to tray is still missing

**Comment by sajjadmrx** [comment]
thank you for your suggestion. 
we will look into it

**Comment by sajjadmrx** [comment]
added [v2.1.0](https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.1.0)
