### ISSUE TITLE
نام برنامه

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#16]
سلام، ممنون که این برنامه را اپن‌سورس منتشر کردید،
اما فکر می‌کنم لزومی نداره که در نام برنامه به این نکته اشاره شود.

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/021a91e2-fad5-41fb-9ea0-f33769c1ad4e)

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/9c3a0b90-fcbf-40aa-857f-f5447a9055eb)

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/3f6755e2-686c-4b60-be59-41c940f918a1)

پیشنهاد می‌کنم عبارت `(OpenSource)` در نام برنامه را حذف کنید.

**Comment by sajjadmrx** [comment]
fixed [v2.1.0](https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.1.0)

**Comment by xmha97** [comment]
Thanks 🙏
