### ISSUE TITLE
پیروی از تم سیستم عامل

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#18]
سلام، من در روزها از تم روشن و در شب‌ها از تم تاریک استفاده می‌کنم. (این تغییر اتوماتیک اتفاق می‌افتد)

می‌خواستم گزینه‌ای اضافه کنید که از تم سیستم عامل پیروی کند:

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/99de166f-d516-4188-b879-6618e40a7b60)

مثل VS Code:
![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/d8d77c89-7a89-41b4-96eb-8633e38f171e)

با تشکر.

**Comment by sajjadmrx** [comment]
added [v2.1.0](https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.1.0)

**Comment by xmha97** [comment]
ممنون، فقط یه نکته:
به درستی از تم ویندوز پیروی میشه اما
در زمان اجرا تم تغییر نمی‌کنه.
می‌تونید این رو هم درست کنید؟
