### ISSUE TITLE
سلکت‌شدن متون برنامه

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#19]
سلام
برخی از متون برنامه سلکت میشن
ممنون میشم درستش کنید
یعنی کاری کنید که دیگه سلکت نشن

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/9184bfe5-83ef-486e-8903-f3f685f200ef)

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/2e3be668-4e46-4ab3-aecd-dc279ba2993b)

**Comment by sajjadmrx** [comment]
fixed [v2.1.0](https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.1.0)

**Comment by xmha97** [comment]
ممنون
