### ISSUE TITLE
امکان ری‌سایز کردن اپ

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#20]
سلام
نمیتونم اپ رو ری‌سایز کنم
لطفا این ویژگی را اضافه کنید.
اگر چه اگر برنامه ری‌سایز شود، اپ به خوبی آن را مدیریت می‌کند و ظاهر مطلوبی دارد.

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/1fcc5d30-d6a0-4af8-84ef-f264875bffe6)

**Comment by sajjadmrx** [comment]
ریسپانسیو نیست! واسه همون امکان ری سایز برداشته شده

**Comment by xmha97** [comment]
آها، نمی‌دونستم.
شاید این فیچر مهم به نظر نرسه اما من همیشه از قابلیت Snap Window یا همون Split Screen استفاده می‌کنم (یعنی این که یه برنامه رو می‌کشم گوشه‌ی صفحه تا تا به سایز مناسب در بیاد)؛ برا اپ‌هایی که ری‌سایز نمیشن این فیچر غیرفعاله که منطقی هم است.
