### ISSUE TITLE
DnsCrypt

### ISSUE THREAD

**Issue by Pakrohk** [DnsChanger/dnsChanger-desktop#25]
اگه بتونید این قابلیت رو به نرم افزار اضافه کنید از نظر امنیتی محشر میشه.

https://www.dnscrypt.org/#dnscrypt-proxy

**Comment by kehiy** [comment]
dnscrypt also need the protocol support from the DNS!
we can do it for all existing servers...
and for using they trusted server list, there is no need to DnsChanger or something like that.
