### ISSUE TITLE
اضافه کردن حالت دارک به منوی انتخاب تم

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#27]
منوی انتخاب تم در حالت دارک، لایته
ممنون میشم به این منو حالت دارک هم اضافه کنید

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/43980353-6bdc-4ddb-8732-7830b070e2d8)

**Comment by sajjadmrx** [comment]
مرسی بابت گزارشتون فیکس شد [3381b2d](https://github.com/DnsChanger/dnsChanger-desktop/commit/3381b2d84f7edd9738abe0e9ea179f7fcc374964)
به زودی منتشر میشه

**Comment by xmha97** [comment]
ممنون از شما 🙏

**Comment by sajjadmrx** [comment]
https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.1.3
