### ISSUE TITLE
برعکس‌کردن سرت فایل چنج‌لاک

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#29]
سلام، سرت فایل چنج‌لاگ رو اگه میشه برعکس کنید 
یعنی آخرین نسخه بالا باشه و اولین نسخه پایین
معمولا افراد فایل رو باز می‌کنند که تغییرات چند نسخه‌ی آخر رو ببینند.

https://github.com/DnsChanger/dnsChanger-desktop/blob/main/changelog.md

مثل این:

https://github.com/LinwoodDev/Butterfly/blob/develop/CHANGELOG.md

**Comment by sajjadmrx** [comment]
ممنون، اوکی شد
