### ISSUE TITLE
UX بهتر

### ISSUE THREAD

**Issue by sajjadmrx** [DnsChanger/dnsChanger-desktop#34]
پیشنهاد کاربر X (توییتر) https://twitter.com/kos_khol/status/1686839793332736000?t=NLZEdIpIkAkAPD36CQrRSA&s=19

اول از همه
دکمه ی اتصال رو میاوردم دقیقا وسط
اون دوتا دیکورد و گیتهاب رو منتقل میکردم اون طرف روی دکمه اتصال
و فضای خالی کادر آبی رو سرتاسر حذف میکردم
تا اون انتخاب dns بیاد کاملا بالا

این بنظرم چینشیه که بیشتر به دل میشینه
![20230803_003430](https://github.com/DnsChanger/dnsChanger-desktop/assets/66132114/1d8cb83a-e4cd-4a39-9090-26c5bbf34997)

شایدم اصلا بهتر باشه اون ارتباط دیسکورد و گیتهاب
ازین صفحه پاک بشن
برن توی تنظیمات
یه تب جدای کانتک باز بشه براشون
چون مخاطب عام برای مطرح نیست اصلا گیتهاب چیه دیسکورد چیه
کسی که دنبالش باشه اونجا بهتر پیداش میکنه

به جاش صفحه ی اصلی برای همه جذاب تر میشه

**Comment by xmha97** [comment]
من پیشنهاد می‌کنم Window Border کاستوم استفاده کنید:

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/61887109-9062-4599-9e43-53ccfb92fd0b)

**Comment by sajjadmrx** [comment]
> من پیشنهاد می‌کنم از Window Border کاستوم استفاده کنید:
> 
> ![image](https://user-images.githubusercontent.com/23485114/258163304-61887109-9062-4599-9e43-53ccfb92fd0b.png)

پیشنهاد خوبیه
اما احساس میکنم  پوزیشن دکمه اتصال خوب نیست!
و پوزیشن دکمه اضافه کردن کاستوم سرور مارو محدود میکنه چون ممکنه بعدا دکمه های بیشتری اضافه بشه ؟
نظری نداری؟

**Comment by sajjadmrx** [comment]
@xmha97 
![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/66132114/afcd865a-7721-4fa7-9d26-2650398b32e3)
بهتر نیست؟

**Comment by xmha97** [comment]
ممنون از نکاتی که اشاره کردید.
بله، این چیزی که شما فرستادید، بهتره.

**Comment by xmha97** [comment]
چقدر UI برنامه خوب شده، ممنون.

![Untitled](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/00ac798d-5d3b-47c1-a5d8-2571757c0ae8)
