### ISSUE TITLE
[Bug]:white screen in V2.1.6

### ISSUE THREAD

**Issue by miladmrk94** [DnsChanger/dnsChanger-desktop#38]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

درهنگام نصب ورژن جدید با white screen روبرو میشم
win10

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
https://github.com/DnsChanger/dnsChanger-desktop/issues/39#issuecomment-1666506861
