### ISSUE TITLE
[Bug]: only white screen appears

### ISSUE THREAD

**Issue by wahitftry** [DnsChanger/dnsChanger-desktop#39]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

Hi I want to report about a dns changer software that only shows white screen after updating to version 2.1.6 from 2.1.4. I have reinstalled but still not working. 

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/26300406/a360cb26-3cdc-49f9-a720-7ca80f6e5cfc)

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
**Thank you for reporting the issue. It has been fixed.** [download new version](https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.1.7)
