### ISSUE TITLE
No User interface.

### ISSUE THREAD

**Issue by BigT2013** [DnsChanger/dnsChanger-desktop#40]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

White box pops-up, but nothing else. No GUI. Tried several times installing and reinstalling.

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
https://github.com/DnsChanger/dnsChanger-desktop/issues/39#issuecomment-1666506861
