### ISSUE TITLE
Add builds x86.

### ISSUE THREAD

**Issue by NikSavchenk0** [DnsChanger/dnsChanger-desktop#41]
so what about x86 builds?

**Comment by xmha97** [comment]
به نظرم یه تلاش بیهوده‌ای هست و مورد استفاده‌ی کسی قرار نخواهد گرفت؛ چرا که الان دیگه همه‌ی کامپیوترها ۶۴ بیت هستن.

**Comment by kehiy** [comment]
@sajjadmrx we should add x86 build also (after adding other Linux package managers)
