### ISSUE TITLE
 Last version scan

### ISSUE THREAD

**Issue by mad-max-98** [DnsChanger/dnsChanger-desktop#42]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

سلام خسته نباشید
نسخه ای که توی VT هست نسخه ی 2.1.2 هست. لطفا آخرین نسخه رو قرار بدید ممنون

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
@mad-max-98 

https://www.virustotal.com/gui/file/3d50c66394a4b620ce874b0520db73a5049ec42142f262c9460d6cdb72e74fe3?nocache=1
