### ISSUE TITLE
ابر گوگل

### ISSUE THREAD

**Issue by MortezaIsvand** [DnsChanger/dnsChanger-desktop#46]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

چرا با هیچ کدوم از سرور ها نمیشه سرویس ابر گوگل را باز کرد؟
https://g.co/kgs/7wFn5S

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
403 رو امتحان کنید
