### ISSUE TITLE
[Bug]: App Icon

### ISSUE THREAD

**Issue by xmha97** [DnsChanger/dnsChanger-desktop#48]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

سلام، در ویندوز بعضی اوقات آیکون برنامه نمایش داده نمی‌شود:
<img width="254" alt="Screenshot 2023-09-19 041400" src="https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/438d4f29-71e9-4e78-9514-d3418c948a48">
<img width="333" alt="Screenshot 2023-09-19 041600" src="https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/88bdad94-a028-4530-a9a1-c4dc6bc0d9ab">
(این اتفاق در منوی استارت ویندوز هم رخ می‌دهد اما من عکس نگرفتم ازش)

دلیلش اینه که آیکون برنامه فقط دارای سایز ۲۵۶×۲۵۶ است و سایزهای دیگه رو نداره!
![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/8583c94c-994c-4a7e-ac2b-7f74946c6b7d)

این سایزها باشه، کافیه:
![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/beab75e9-86f5-44ce-b334-a2212a3c3db6)

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other
دو تا نکته

اول این که آیکون برنامه رو با هر ابزار یا اپلیکیشنی که بسازید، اوکیه اما من اپ زیر رو توصیه می‌کنم:
http://greenfishsoftware.org/gfie.php

دوم این که آیکون‌ها باید بر اساس سایز سورت بشن مثل آیکون اج (که عکسش رو بالا گذاشتم)
در غیر این صورت آیکون نمایش داده میشه اما ممکن است بی‌کیفیت نمایش داده بشه

بدترین حالت اینه که مثل برنامه‌ی زیر سورت برعکس باشه
![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/23485114/9c865300-03e4-4d2a-bd53-261878bb3108)

**Comment by xmha97** [comment]
سلام، می‌خواستم آیکون رو بسازم اما تو سورس کد برنامه آیکون SVG رو ندیدم.
به جز فایل‌های موجود چیز دیگه‌ای دارید که کمک کنه؟ مثلا فایل فوتوشاپ و...
پ.ن: ری‌سایز کردن عکس در سایزهای مختلف مطلوب نیست، آیکون باید در سایزهای مختلف رندر بشه.

**Comment by xmha97** [comment]
سلام، می‌خواستم آیکون رو بسازم اما تو سورس کد برنامه آیکون SVG رو ندیدم.
به جز فایل‌های موجود چیز دیگه‌ای دارید که کمک کنه؟ مثلا فایل فوتوشاپ و...
پ.ن: ری‌سایز کردن عکس در سایزهای مختلف مطلوب نیست، آیکون باید در سایزهای مختلف رندر بشه.
@sajjadmrx

**Comment by sajjadmrx** [comment]
سلام، نه متاسفانه فایل SVG نیست
درمورد فایل psd فتوشاپ باید از گرافیک دیزاینر بپرسم و تا فردا تو دیسکورد بهتون خبر میدم.
اما فایل های png,ico در مسیر https://github.com/DnsChanger/dnsChanger-desktop/tree/main/public/icons هستن
