### ISSUE TITLE
DNS Changer for phones?

### ISSUE THREAD

**Issue by muhammadbahaa2001** [DnsChanger/dnsChanger-desktop#55]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

Will we see DNS Changer for Android & iOS?

### 💻 In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
Yes, soon 👌
