### ISSUE TITLE
Add these features to your application

### ISSUE THREAD

**Issue by OrchidWarrior** [DnsChanger/dnsChanger-desktop#58]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

Please add these features to your DNS changer for a better experience:

1- Flush DNS Resolver Cache
2- Flush ARP Cache

your application should apply those after changing DNS

### 💻 In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by sajjadmrx** [comment]
added https://github.com/DnsChanger/dnsChanger-desktop/releases/tag/v2.3.0
