### ISSUE TITLE
Every time i want to connect I have to input my password[Parser]:

### ISSUE THREAD

**Issue by zamaniafshar** [DnsChanger/dnsChanger-desktop#64]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

Thank you, guys, for this great app. I'm using Ubuntu, and every time I want to connect to a DNS, I have to input my password, which is annoying. If it's possible, I'd like to input my password only the first time I run the app.

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/88077166/3bc693da-1a1e-4583-8714-9f67652f6315)

### 💻 In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by OrchidWarrior** [comment]
To turn off autologin:

Head to "Settings" - "Users" tab
Click the "Unlock" button: you must provide your password.
Turn the checkmark next to "Automatic login" off.
