### ISSUE TITLE
چند پیشنهاد برای برنامه دی‌ان‌اس چنجر

### ISSUE THREAD

**Issue by KEANU2003** [DnsChanger/dnsChanger-desktop#65]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

سلام و خسته نباشید.
برنامه‌ی DNSChanger واقعا فوق‌العادس😎👌
تمام سرویس با پینگ‌های خیلی پایین و با سرعت خیلی بالا کار می کنن
واقعا بنظرم کار رو همچین برنامه‌ای زحمت زیادی داشته
چون که خودمم دانشجوی مهندسی کامپیوتر هستم اینو به خوبی می دونم
چند تا ایده و پیشنهاد داشتم که خیلی ممنون می شم اگه بررسیشون کنید و درصورتی که امکانش بود انجامشون بدید:

۱.نسخه‌ی windows این برنامه خیلی خوب کار می کنه من در واقع الان این برنامه‌رو به عنوان مرجع تمام dnsها می شناسم و تازه از اون بهتر میشه dnsهای جدید هم بهش اضافه کرد ولی واقعا چقدر عالی و بی نقص می شد اگر این برنامه یک نسخه‌ی اندروید هم داشت...من از اون هم در صورت انتشار حمایت می کنم ✊️💪

۲.بعضی وقتا کاربر قصد داره دو تا dns رو که از یجایی مثل تلگرام کپی کرده و داخل کلیپبوردش قرار داده سریع و بی دردسر داخل برنامه پیستش کنه ولی متاسفانه تا جایی من فهمیدم برنامه همچین قابلیتی نداره...اگر امکانش هست این مشکل رو هم برطرف کنید.

باتشکر فراوان از سازنده‌ی برنامه🙏

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Redruby110** [comment]
3-Adding Auto Scan option, so app could scan each group of user's selected DNS based on time schedule and sets fastest DNS.(same as "Netoptimizer" android app)
