### ISSUE TITLE
[Bug]: حجم زیاد برنامه

### ISSUE THREAD

**Issue by itskazemk** [DnsChanger/dnsChanger-desktop#67]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

حجم برنامه به طرز عجیبی زیاده

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
سلام به خاطر تکنولوژی هست که استفاده شده
خیلی از برنامه های دیگ هم به این صورت هستن
باز اگه راهی بود سعی میکنم فشرده ترش کنم

**Comment by kehiy** [comment]
@itskazemk 
- #45
