### ISSUE TITLE
انتخاب محل نصب

### ISSUE THREAD

**Issue by itskazemk** [DnsChanger/dnsChanger-desktop#69]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### 🪄 describe your feature or idea

چرا نمیشه محل نصب برنامه رو انتخاب کرد؟ من نیمخوام داخل درایو c نصب بشه (ویندوز)

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by xmha97** [comment]
+1
