### ISSUE TITLE
[Bug]:زمانبر بودن بالا اومدن نرم افزار 

### ISSUE THREAD

**Issue by MirS0bhan** [DnsChanger/dnsChanger-desktop#78]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

برای اجرا شدن نرم افزار خیلی زمان میبره ۳ دقیقه عینا زمان میبره 
مشخصات سیستم :
-  ۱۶ گیگ رم ddr3
- core i5 6
- arch

### 💻 In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by h3li0p4us3** [comment]
سلام دوست عزیز. بهتون پیشنهاد میکنم از نسخه CLI اپ استفاده بکنید

**Comment by sajjadmrx** [comment]
3 دقیقه!
از این بابت مطمعنید؟
من واسه لینوکس نسخه cli رو پیشنهاد میکنم 
به زودی داکیومنتش رو بهبود میدم
https://github.com/DnsChanger/dnschanger-cli

**Comment by h3li0p4us3** [comment]
> 3 دقیقه! از این بابت مطمعنید؟ من واسه لینوکس نسخه cli رو پیشنهاد میکنم به زودی داکیومنتش رو بهبود میدم https://github.com/DnsChanger/dnschanger-cli

احتمال خیلی زیاد مشکل از سمت خودشونه چون برای من کلا ۱ ثانیه هم طول نمیکشه

**Comment by MirS0bhan** [comment]
> 3 دقیقه! از این بابت مطمعنید؟ من واسه لینوکس نسخه cli رو پیشنهاد میکنم به زودی داکیومنتش رو بهبود میدم https://github.com/DnsChanger/dnschanger-cli


فن کامپیوتر صداش در میومد 
یک دقیقه اول فقط یک صفحه سفید بود 
و تیکه تیکه همه چی بالا میومد 
و در نهایت یه مشکل دیگه هم این بود که وقتی تب صفحه رو عوض میکردم کلا خاموش میشد
