### ISSUE TITLE
[Bug]: Unknown error while connecting

### ISSUE THREAD

**Issue by SEYED1424** [DnsChanger/dnsChanger-desktop#82]
### 🤔 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Discription

درود. وقتی روی دکمۀ کانکت میزنم این ارور بهم داده میشه که معلوم نیست مشکل از کجاست اصلا. 
ویندوز 11

![image](https://github.com/DnsChanger/dnsChanger-desktop/assets/99642593/7d26afbf-63f2-432b-bd28-70864d8a2ac0)

### 💻 In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by sajjadmrx** [comment]
https://github.com/DnsChanger/dnsChanger-desktop/issues/74
